a = int(input("Enter the number : "))
b = int(input("Enter the number : "))

print("Sum of a and b is : ", a+b)
print("Minus of a and b is : ", a-b)
print("Multiply of a and b is : ", a*b)
print("Division of a and b is : ", a/b)
print("Floor division of a and b is : ", a//b)
print("Modules of a and b is : ", a % b)
print("Power : ", a**b)
